discord:
  prefix: "!"
  cogs:
    events_organizer: "events_organizer"
    ping: "ping"
    config_manager: "config_manager"

config_path: "configs"
config_file:
  common: "common.yaml"
  default: "config.yaml"
  local: "config.local.yaml"
  prod: "config.prod.yaml"
cogs_dir: "./cogs"
language: "es"
locales_path: "locales/"
aliases_file: "locales/aliases.json"
